### ISSUE TITLE
遠征可否チェック

### ISSUE THREAD

**Issue by yuno-san1** [gre4bee/ElectronicObserver#100]
別窓で表示される遠征可否チェックのフォントサイズは変更出来ないのでしょうか？

**Comment by myangelkamikaze** [comment]
Ah, this window right?
![image](https://user-images.githubusercontent.com/40002167/150677131-60327919-6b9b-4f84-b7b5-a8c66facd0c9.png)

It looks like the font size is hardcoded currently, so it's not possible to change. The correct behavior would probably be to use the same size as メインフォント. We'll fix this for the next release.

**Comment by myangelkamikaze** [comment]
Expedition check will use メインフォント in the next release.
Example with font size 24px:
![image](https://user-images.githubusercontent.com/40002167/151290961-e0b73775-f045-4ca7-bc29-84534a943352.png)
