### ISSUE TITLE
任務欄のクラッシュについて/About the crash of the mission column

### ISSUE THREAD

**Issue by KimidoriBoushi** [gre4bee/ElectronicObserver#101]
はじめまして。
gibhub自体が始めてなので間違ってるかもしれませんがご容赦願います。英語も苦手なのでDeepl使って日本語と英語併用してます。

先日より利用させていただいているのですが、任務欄にバグかもしれないものを発見しました。
出撃系任務を受領し、完了時に任務欄がクラッシュします。
次のようなエラーを出しました。　エラー文章は長いのでテキストファイルでこちらにアップロードします。
出撃関連の任務以外では今の所発生しておりません。

これから長くお世話になると思いますが、これからもよろしくおねがいします。

Nice to meet you.
I'm not good at English, so I use Deepl for both Japanese and English. I'm also not very good at English, so I'm using Deepl to use both Japanese and English.

I've been using it for a while now, but I found what might be a bug in the mission section.
When I receive a sortie mission and complete it, the mission field crashes.
I got the following error.　The error text is long, so I'll upload it here as a text file.
This has not happened to me so far, except for sortie related missions.

I'm sure you will be around for a long time to come, and I look forward to working with you.

Translated with www.DeepL.com/Translator (free version)

[メモ.txt](https://github.com/gre4bee/ElectronicObserver/files/7962876/default.txt)

**Comment by myangelkamikaze** [comment]
Thanks for the report!
You can write in Japanese if you want, it's not a problem at all.

We're currently reworking the quest view, so the error should be fixed when that's done.

**Comment by KimidoriBoushi** [comment]
日本語大丈夫でしたか、ありがとうございます。
これからもよろしくおねがいします。

これはクローズするべきでしょうか？

**Comment by myangelkamikaze** [comment]
No, you can keep it open. I'll close it when we get the fix done ・。・ｖ

**Comment by KimidoriBoushi** [comment]
了解しました。

**Comment by myangelkamikaze** [comment]
Quest view has been remade in version 5.1.1 so this should be fixed.
