### ISSUE TITLE
borderless notification dialog not working

### ISSUE THREAD

**Issue by dnwldnwl2** [gre4bee/ElectronicObserver#102]
![db](https://user-images.githubusercontent.com/42876613/151650854-cbce51a6-0ea1-4739-ac9a-e435006ee857.PNG)

In version 5.1.0, the function to output only image without borders in the notification dialog does not work. I don't know if this is a new issue with this version as I've never used it before. All other functions appear to be working fine.

**Comment by myangelkamikaze** [comment]
It looks like borderless + image don't work together. Checked back to version 4.6.0, and it doesn't work there either.
I don't notice any difference when border is displayed and not on win10, so I'm not sure what that option does.

**Comment by dnwldnwl2** [comment]
![b](https://user-images.githubusercontent.com/42876613/151685745-4ea2a99b-6704-40ff-bb23-f6790b40784e.png)

The difference stands out when using images with transparent backgrounds. The left image shows the wallpaper, while the right image shows the gray screen of the dialog together.

**Comment by myangelkamikaze** [comment]
I see. This is working in the original 74EO(七四式)? In the latest version?

**Comment by dnwldnwl2** [comment]
Yes, I confirmed that it works on the original 74EO (latest==4.7.1) In addition, I am using Windows 10.

**Comment by myangelkamikaze** [comment]
This has been fixed now. The fix will be available in the next version.

![image](https://user-images.githubusercontent.com/40002167/152972121-2512f2dc-2f62-49bd-81af-98954b3f07ba.png)
