### ISSUE TITLE
任務ウィンドウでチェックボックスが表示されない

### ISSUE THREAD

**Issue by Memory-of-Snow** [gre4bee/ElectronicObserver#104]
任務ウィンドウで遂行中の任務と、それ以外の任務の区別ができない状況です。
これは仕様でしょうか？何か、解決策・回避策はありますか？

![2022y01m29d_145053930](https://user-images.githubusercontent.com/98633948/151653254-63a948d7-7033-4c12-80f4-53e4cf5a12da.jpg)

**Comment by myangelkamikaze** [comment]
This doesn't look correct, no.
A possible workaround is to only display accepted quests.
![image](https://user-images.githubusercontent.com/40002167/151654246-3459dd9b-2446-4b6b-be1b-fc89a6ad4856.png)

We're reworking the quest view, so the bug will probably be fixed when we finish it. We're not sure when exactly it will be done right now.

**Comment by Memory-of-Snow** [comment]
I see.Thanks.

**Comment by myangelkamikaze** [comment]
I'll keep this open until we fix it ・。・ｖ

**Comment by myangelkamikaze** [comment]
We remade the quest view in version 5.1.1 so this should be fixed.
