### ISSUE TITLE
ミュートボタンについて

### ISSUE THREAD

**Issue by daix2z** [gre4bee/ElectronicObserver#105]
はじめまして。
先日よりEN版を使い始めたのですが、以下の現象が発生しております。

1.ミュートボタンをクリックしてミュート状態にします
2.通知イベントでダイアログが表示されます
3.その後ミュートボタンをクリックして解除してもゲーム音が再生されないです
![image](https://user-images.githubusercontent.com/87525340/151667718-dafe6c13-7bdd-4f32-82b0-2ff73e94f9f6.png)

ミュートボタンのオフ-オンを繰り返す場合は問題なくゲーム音は再生されます
設定画面で試した場合も問題なくゲーム音は再生されます。

こちらについてご確認及びご対応頂けますでしょうか。
よろしくお願いいたします。

Version 5.1.0.0
Windows10

**Comment by myangelkamikaze** [comment]
Thanks for the report!
We have a fix ready for version 5.1.1. A preview version was released just now, full release is expected next week.

**Comment by daix2z** [comment]
Thank you for your prompt confirmation and response!

**Comment by myangelkamikaze** [comment]
Version 5.1.1 has been released now so this problem should no longer occur.
