### ISSUE TITLE
最前面表示の不具合

### ISSUE THREAD

**Issue by KimidoriBoushi** [gre4bee/ElectronicObserver#106]
ブラウザを最前面に指定していると、バージョン情報等の別に開くウィンドウがブラウザの下に行き、その下に行ったウィンドウが操作できず、最前面の本体は操作を受け付けず、強制終了以外に何もできなくなります。

**Comment by myangelkamikaze** [comment]
Thanks for the report, I confirmed this happens and will look for a fix.

**Comment by KimidoriBoushi** [comment]
忘れてましたが、レイアウト変更時にも、変更するウィンドウのほうが下に行ってしまってレイアウトの変更ができなくなります。
