### ISSUE TITLE
Fleet info bar "hide" fleet AA info when it displays too much info

### ISSUE THREAD

**Issue by kafe523** [gre4bee/ElectronicObserver#107]
Sorry for the poor English and the bad title. 🙇‍♂️ 

When the fleet info bar has to display a lot of information. It will push the "fleet AA" icon to the right. And I can't access it even when I grab the bar to the right.

This happens in both English and Japanese UI.

This is how it looks in Japanese UI
![image](https://user-images.githubusercontent.com/20486186/151705823-9f3dc4f1-e64e-42d8-b6f8-e5d790fb2c12.png)

in English UI
![image](https://user-images.githubusercontent.com/20486186/151706269-679ab494-6bd1-4e41-95d6-f76016c294b3.png)

<br>

The layout I used is imported from the original 74EO(4.7.1) and it works fine in there.
Because the scroll bar also scrolls the info bar.
That I can access the Fleet AA info.

May you notice the issue. Thank you. 🙇‍♂️

**Comment by myangelkamikaze** [comment]
There's an option to collapse text, which should be able to display everything. Does that solve your problem?

![image](https://user-images.githubusercontent.com/40002167/151727185-b852058b-52eb-4dc2-9e10-587efdc476b6.png)

**Comment by kafe523** [comment]
It works well by switching the setting you mention.
Here is the result.

in Japanese
![image](https://user-images.githubusercontent.com/20486186/151756830-f299d8a3-33c9-4b72-8282-ce9d0c60e88f.png)

in English
![image](https://user-images.githubusercontent.com/20486186/151757283-d59f1830-742e-4ad4-b03e-61b1b93067ce.png)

Thanks again for helping! 🙇‍♂️
