### ISSUE TITLE
Ship groups do not sort independently

### ISSUE THREAD

**Issue by Nobuchina** [gre4bee/ElectronicObserver#108]
Hello, just recently switched to this EN version, and thank you for the continuous maintenance.

There is an issue in ship groups of which I am not sure whether it is a bug or an intended design.

Let say I have one group with all ships and one group with only BB.

1. Sort all ships based on level
<img width="203" alt="20220131_113224" src="https://user-images.githubusercontent.com/98725028/151735423-8ee6c60b-d03e-4801-b67e-57e0d5a7a33f.png">

2. Switch to BB group
<img width="202" alt="20220131_114018" src="https://user-images.githubusercontent.com/98725028/151735703-12013638-8ea7-4b47-a9cf-ca60dcbdbe46.png">

3. Switch back to all ships group and all BBs are on the top
<img width="202" alt="20220131_114138" src="https://user-images.githubusercontent.com/98725028/151735787-adcbc537-28c1-4c7c-99a5-54b0ea2098ca.png">

**Comment by myangelkamikaze** [comment]
I think this is a bug, we'll look into it.

**Comment by myangelkamikaze** [comment]
I looked into this but I can't reproduce the bug. I also compared the sorting behavior with the original version and it looks the same.
When switching groups, the sort will be set to the default auto sort value, which can be found in the right click menu.
![image](https://user-images.githubusercontent.com/40002167/152937343-566b7615-8ada-4462-ad0b-a3424a250a14.png)
![image](https://user-images.githubusercontent.com/40002167/152937376-a90ee0fa-c73b-413d-a89a-78810570f66a.png)

**Comment by Nobuchina** [comment]
Thanks for investigating. Actually I removed the criteria in my auto sort.

I guess the issue here is that,
if there is no criteria in auto sort (or auto sort is disabled),
it will still auto sort by ID (with a behaviour to keep ships from previous group on top if they exist in new group).

In the original version, without auto sort, the ship groups will retain the order I left.

1. Sort CV group by any order (level for example)
2. Switch to BB group and sort by any order (HP for example)
3. Switch back to CV group will retain the order by level (although the upward arrow is still in HP column but does not really matter)
<img width="199" alt="20220208_212453" src="https://user-images.githubusercontent.com/98725028/152996167-8dddbe1f-a6da-4b73-9aa5-d35ea3dc5ca7.png">

In the EN version, perform step 1-3, CV group will be sorted by ID.
<img width="201" alt="20220208_224103" src="https://user-images.githubusercontent.com/98725028/153009676-24205600-3bcc-4076-a9ed-c3f185e2f079.png">

Alternatively in step 3, if switch to all ship group instead of CV, all BB will remain on top by HP and the rest are at bottom by ID (regardless of the original order), which is the same behaviour in my original comment
<img width="199" alt="20220208_230411" src="https://user-images.githubusercontent.com/98725028/153014321-56b96e1f-47e4-4048-a855-5061bdc82ee4.png">

**Comment by myangelkamikaze** [comment]
Thanks for the extra details. I could reproduce the error and will look for a fix.

**Comment by myangelkamikaze** [comment]
The fix will be available in the next version.

**Comment by Nobuchina** [comment]
Thanks a lot for the fix!
