### ISSUE TITLE
When Fleet state is critical damage and setting is blink, its display incorrect

### ISSUE THREAD

**Issue by thorloki4** [gre4bee/ElectronicObserver#109]
Sorry for the poor English.

When the fleet state is critical damage or expedition completion, and setting is blink, it seems doesn't apply color of ColorScheme.json.
Maybe RefreshFleetState,UpdateFleetState in FleetStateViewModel need to modify, also StateLabel need to set back foreColor.

Thank you for the continuous maintenance.

**Comment by myangelkamikaze** [comment]
ColorScheme.json only gets used when you're using the custom theme option. Are you maybe using light or dark theme instead?
Note: custom theme is currently dark theme based, so if you have colors made for light theme the result probably won't look good.

![image](https://user-images.githubusercontent.com/40002167/151746169-bb54fee8-30e3-482f-8691-46cbdbcbadf3.png)

**Comment by myangelkamikaze** [comment]
Checked now, you're correct, we don't use the custom color, it's hardcoded: https://github.com/gre4bee/ElectronicObserver/blob/main/ElectronicObserver/Window/Wpf/Fleet/ViewModels/FleetStateViewModel.cs#L58

More or less the same thing is happening in RefreshFleetState. We'll update that.

**Comment by thorloki4** [comment]
Thank your confirmation and response :)
