### ISSUE TITLE
演習ログについて

### ISSUE THREAD

**Issue by daix2z** [gre4bee/ElectronicObserver#114]
先日はご対応いただきありがとうございました
今度は別の不具合になります。
演習ログが正しく表示されない状態になっています(艦娘Expが表示されないです)
出撃した場合のログは正しく表示されています

![image](https://user-images.githubusercontent.com/87525340/152693185-541907da-639d-4b71-bd63-d355919c6b08.png)

こちらについてご確認及びご対応頂けますでしょうか。
よろしくお願いいたします。

Version 5.1.1.0

**Comment by myangelkamikaze** [comment]
We added the missing text, the log should be displayed correctly in the next version.

**Comment by daix2z** [comment]
Thank you for your response!
