### ISSUE TITLE
Higher CPU load than 74eo

### ISSUE THREAD

**Issue by RyzeVia** [gre4bee/ElectronicObserver#115]
I migrated my kancolle environments from 74eo to 74en.
Then, I got very high cpu load from MS Edge WebView2.
Is it normal behavior? If it is yes, are there some configuration for reducing the CPU load ?

My environments is:
OS: Windows 10.0.19043.1466
CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz   2.11 GHz
RAM: 24.0 GB
WebView2: 98.0.1108.43 ( On first 74en starting, 74en downloaded it automatically.)

CPU Load by 74en:
![FLDYVhNaIAQgtA_](https://user-images.githubusercontent.com/17078638/152929899-427d08d9-c90b-48e5-a410-69a35a62c662.jpg)

CPU Load by 74eo:
![FLDX70_aIAAxRSq](https://user-images.githubusercontent.com/17078638/152929967-ff8fd212-06f9-4433-9e97-291adff6f2df.png)

**Comment by myangelkamikaze** [comment]
Hmm interesting, your CPU doesn't seem to be that old. We had a case of this previously on a much older CPU.The high CPU load comes from chromium software rendering, which was switched to vulkan in version 94.

First make sure you have hardware acceleration enabled, it's enabled by default so it should be enabled unless you disabled it.

If that doesn't solve it, try using this option, it's made for this bug. It will disable the vulkan software rendering by renaming the required files from the WebView2 folder (which can be in either program files or local application data folder).

![image](https://user-images.githubusercontent.com/40002167/152933502-23497816-8ffa-4072-a2e1-a8166adcaa53.png)

You can look at this twitter thread if you want to do this manually: https://twitter.com/MyAngelKamikaze/status/1482320324804988933

**Comment by RyzeVia** [comment]
Thank you for reply,
The hardware acceleration flag had been off.
For turning up it, our kancolle environments are completely well-worked.
I apologize for any inconvenience caused by this minor mistake.

Thank you for your kindness, and God bless you and also your KAMIKAZE

![スクリーンショット 2022-02-08 170110](https://user-images.githubusercontent.com/17078638/152943442-07004d30-7102-45ee-b254-697a3aea7b30.png)
.
