### ISSUE TITLE
明石による泊地修理について

### ISSUE THREAD

**Issue by KimidoriBoushi** [gre4bee/ElectronicObserver#117]
リクエストです。
HPが満タンになった艦だけ、色が変わるようにしていただけると、非常に助かります。

必須というわけではないのですが、余力があるときにでも宜しくおねがいします。

**Comment by myangelkamikaze** [comment]
Like this right? The fix will be available in the next release.

![image](https://user-images.githubusercontent.com/40002167/153527519-e5d216d0-0ad6-4545-8ac0-985417bab9e6.png)

**Comment by KimidoriBoushi** [comment]
Thank you
