### ISSUE TITLE
戦闘画面の敵味方が広い？

### ISSUE THREAD

**Issue by KimidoriBoushi** [gre4bee/ElectronicObserver#120]
要望です。

今回のイベント始まって急に意識するようになったのですが、戦闘のウィンドウについてです。
下画像の下列真ん中のウィンドウです。

ちょっと敵味方の艦隊状況表示が広いかなーと。
空欄部分に味方第二艦隊と、敵第一艦隊が入るのは分かるのですが

双方連合でない時や
片方が連合でない時は
表示詰めていただけると助かります。

必須といういことは全然ないので、余裕があるときにでもご検討いただけますと幸いです。

![20220225214007](https://user-images.githubusercontent.com/66873075/155717281-2a8e2b33-bd41-4d44-866c-4f24fc855390.jpg)

**Comment by myangelkamikaze** [comment]
Thanks for the report!
This was mentioned in discord and we added a fix for it. We still need to test it, but the fix will be available in the next version.

**Comment by y-jin-yoshihiko** [comment]
I want to request additional on the battle window.

Now, the battle window is not easy to differentiate between an enemy ship with a little HP or 0 HP.
![battlewindow1](https://user-images.githubusercontent.com/92554600/157782798-ac017776-42f1-45fa-a964-67b8df39396d.png)


So, I want to change the background color of the sinking enemy's HP.
(The below image is edited with MS Paint.)
![battlewindow2](https://user-images.githubusercontent.com/92554600/157782821-e320067c-80eb-44c8-9506-3c65cd88f377.png)

**Comment by myangelkamikaze** [comment]
Can you open a new issue for the different background please?

**Comment by y-jin-yoshihiko** [comment]
I understand, I created a new issue.
