### ISSUE TITLE
サブウィンドウ：艦隊

### ISSUE THREAD

**Issue by yuno-san1** [gre4bee/ElectronicObserver#128]
艦隊表示の各項目にマウスカーソルを合わせると以前は詳細表示が消えなかったと思うのですが
今は一瞬で消えてしまいます。
右クリック等の参照は問題ないのですが、数字の確認がちょっとつらいです。

私の見る限りでは、他のサブウィンドウでは問題が発生していません。

**Comment by myangelkamikaze** [comment]
Does this happen for all tooltips in fleet view or only certain ones?
I can't reproduce the problem.

**Comment by sobrmsy** [comment]
私も[yuno-san1](https://github.com/yuno-san1)さんと類似の事象が発生しています。  
私の環境では艦隊表示だけでなく、全てのホバーが一瞬だけ表示され、すぐに消えてしまいます。  
どうも、高DPI下で発生する様で、プロパティで「高DPIスケール設定の上書き」で「システム」にするとホバーが正常に表示されます。しかし、これでは文字がぼやけるので、対応いただけると幸甚です。  
3/9あたりから発生しはじめたので、Windowsアップデートが関係しているかもしれません

**環境**
* ElectronicObserver  5.1.2.0
* Windows11 Pro 21H2 ビルド 22000.556
* CPU　Ryzen 5 5600X
* RAM	32GB

**Comment by yuno-san1** [comment]
前回まで5.1.1でした。
今朝きがついたので本日、5.1.2へUpdateを行ってみましたが症状は変わらず
すべての表示で一瞬しか表示しなくなりました。
3/10頃にWindowsのアップデートが合ったような気がします。
それより前の状態は思い出せないのが申し訳ない。
七四式は3840x2160の領域にて展開しています。

・環境（化石ではありますが）
Windows 10 Home 21H2　19044.1586
Intel Corei7 CPU 970 　RAM24GB
GPU GeForceGTX 1080  Driver 471.68
3840x2160(150%) ＋ 他2枚のFHD

**Comment by myangelkamikaze** [comment]
Can you check which version of .NET you have installed? I think this could be the problem: https://github.com/dotnet/wpf/pull/6063#issuecomment-1065080375

Write ".NET" in the search box of Apps and features
![image](https://user-images.githubusercontent.com/40002167/158064827-6ebce734-b087-44ac-aa87-1cfdb7f96a18.png)

It should look something like this, and should say either ".NET Runtime 6.0.x" or ".NET Desktop Runtime 6.0.x"
![image](https://user-images.githubusercontent.com/40002167/158064865-a08c6099-2903-46f7-b246-f40e3e71e0da.png)

**Comment by yuno-san1** [comment]
.netのバージョン確認がうまくできなかったので
最新の6.0.3ランタイムを入れてみましたが改善しませんでした。

**Comment by myangelkamikaze** [comment]
The issue I linked says that the problem started showing up in 6.0.3.
I'm currently using 6.0.1 and can't reproduce the problem, so I think that one should work for you too.

**Comment by yuno-san1** [comment]
6.0.3をアンインストールして6.0.1をインストールしたところ、治りました。
ありがとうございました。

.NETって他のことには使ってないのでアップデートしないようにするには何か処置は必要ですか？

**Comment by myangelkamikaze** [comment]
I think windows will try to update it, but I don't really know how to prevent that. I hope the bug will be fixed soon so we don't have to rely on older versions.

**Comment by yuno-san1** [comment]
さて、困りました。
WindowsUpdateで6.0.3のセキュリティ関連で自動的に6.0.1から6.0.3へアップデートされてしまいます。
Windows更新停止以外の処置はありますか？

**Comment by myangelkamikaze** [comment]
If you go under "Advanced options" in Windows Update, there's an option to recieve updates for other Microsoft products when you update Windows. I think it you disable that option it will prevent Windows from updating .NET. If that doesn't work then the only option left is to temporarily disable updates until this is fixed in .NET.

**Comment by yuno-san1** [comment]
更新オプションを切ってても反映されてしまうので定例アップデートで必要なのが来ない限り
自動更新を停止させることにします。
ありがとうございました。

**Comment by myangelkamikaze** [comment]
Looks like this bug will probably be fixed in 6.0.5.
source: https://github.com/dotnet/wpf/issues/6220#issuecomment-1078072569

**Comment by myangelkamikaze** [comment]
https://github.com/gre4bee/ElectronicObserver/issues/158#issuecomment-1124533802
