### ISSUE TITLE
"Apply Stylesheet" does not capture the correct part of the screen

### ISSUE THREAD

**Issue by Heinrike** [gre4bee/ElectronicObserver#131]
When "apply stylesheet" is checked, the incorrect portion of the webpage is captured, leaving a strip of white across the top of the browser window and cutting off the bottom part of the game screen.
![eo](https://user-images.githubusercontent.com/1284440/158302421-c638d214-dfbf-4791-85ed-a69251fbc734.png)
.

**Comment by myangelkamikaze** [comment]
This is a WebView2 bug in older versions. Make sure you have the latest version installed.

**Comment by Heinrike** [comment]
I tried installing the newest version off Microsoft's website and restarted my computer, and the problem persists. Just to make sure, is 99.0.1150.39 the version I should be using?

**Comment by myangelkamikaze** [comment]
Ah, sorry, I worded it badly. You need the lastest EO version.

**Comment by Heinrike** [comment]
Oh, sorry, I suppose I should have checked. Thanks, that solved the problem.
