### ISSUE TITLE
キャッシュクリアができない

### ISSUE THREAD

**Issue by mamicolt** [gre4bee/ElectronicObserver#136]
キャッシュクリアのボタンを押しても何も反応がなくブラウザが再起動しないです

**Comment by myangelkamikaze** [comment]
We need to update the text for the cache clear option.
We changed cache clearing to work like in normal browsers, so the browser doesn't need to get restarted anymore. After clearing the cache, you can just refresh.

**Comment by mamicolt** [comment]
そういう仕様になっていたのですね了解しました
ありがとうございます

**Comment by myangelkamikaze** [comment]
It looks like this now:
![image](https://user-images.githubusercontent.com/40002167/160231598-6f17f6ed-f8c7-4cb5-970d-1255ab2ff02f.png)
![image](https://user-images.githubusercontent.com/40002167/160231613-e6d99cf8-3633-480d-9b5e-1c5f806db0ec.png)
