### ISSUE TITLE
Not able to turn on the friendly fleet

### ISSUE THREAD

**Issue by zEr0xD11294** [gre4bee/ElectronicObserver#138]
Not able to turn on the friendly fleet after update (I already restarted the game and cleared the cache of MS Edge)
What should I do to solve this problem?
![1](https://user-images.githubusercontent.com/102187502/159571534-0f25a271-6176-43e8-8cd4-6a1d02a526ad.jpg)

**Comment by myangelkamikaze** [comment]
open devtools, go to network tab, enable that checkbox
refresh
when you're back on the main screen, disable the checkbox and close devtools
make sure to keep devtools open while you're refreshing
(note: this is basically clearing cache without actually clearing it, clearing Edge cache  doesn't clear WebView2 cache)
![image](https://user-images.githubusercontent.com/40002167/159601692-c3ebee3f-eb1d-48bf-a266-4cd9de2dda61.png)
![image](https://user-images.githubusercontent.com/40002167/159601705-c9b4ab20-8235-49b3-83e8-2b7e44bf4c22.png)

**Comment by zEr0xD11294** [comment]
Thank you so much!
