### ISSUE TITLE
艦船図鑑に登録されない

### ISSUE THREAD

**Issue by hiyo13** [gre4bee/ElectronicObserver#143]
所持しているNelson改の画像データが保存されていません。
陸奥改二でも同様の問題が起きていて、他の艦でも似たような現象が発生する可能性がありそうです。

画像ビューアを開いても同様に編成時のアイコンが登録されていませんでした。
![艦船図鑑](https://user-images.githubusercontent.com/102614288/160677100-9cb77114-1a7e-4a25-8afd-1568a368bbb7.png)

**Comment by myangelkamikaze** [comment]
Other images get saved correctly?
You have this option enabled?
If you have this option enabled and other images get saved correcty, then the images that don't get saved are probably cached by the browser, so 74EO(七四式) can't save them.
![image](https://user-images.githubusercontent.com/40002167/160725275-45c08362-c038-4349-bbf7-22a16289c5c8.png)

You can temporarily disable cache to force the images to get loaded again. Enable that option in DevTools and then move to the organization screen in the game again, and it should get saved correctly.
![image](https://user-images.githubusercontent.com/40002167/160725555-ade95973-f075-483f-bad0-fd84f8a8bdcd.png)
![image](https://user-images.githubusercontent.com/40002167/160725628-2ee64e45-d2fa-48b8-a01b-676fed0c49dc.png)

**Comment by hiyo13** [comment]
無事に記録されました！ 丁寧な対応ありがとうございました。
