### ISSUE TITLE
Browser needs disable to search window open using ctrl+F

### ISSUE THREAD

**Issue by y-jin-yoshihiko** [gre4bee/ElectronicObserver#151]
In 74EN's browser, press ctrl+F to open the search window.

If this opens, the browser cannot operation.
Sometimes the search window's x button cannot press, and in this case, to recover, it is need to start captcha by ミ田+shft+S.

So in this case, I think the browser needs to add to disable ctrl+F.
![kensaku-window](https://user-images.githubusercontent.com/92554600/162850700-1f2ea748-07db-4d76-948c-ec08877feefd.png)

**Comment by myangelkamikaze** [comment]
The fix will be available in the next release.
