### ISSUE TITLE
Add functions to the groups request

### ISSUE THREAD

**Issue by y-jin-yoshihiko** [gre4bee/ElectronicObserver#152]
I want to add to the "Groups" to manage the "damaged ship" in 74EN.

1. add a column "Time required to restore 1 HP".
  →This is used " Akashi Preset Repair" to find the ship 
    for more than 20 minutes for 1HP. ( because it is highly efficient).

2. I want the group to be updated at the time of changing the fleet formation as well.
  →Now "Groups" update timing of the home port display.
    But I want the "Group" to be updated 
    at the timing of the fleet formation of Akashi repair and the docking as well, 
    like the " Fleet" window.

**Comment by myangelkamikaze** [comment]
Time required to restore 1 HP added. It's also available for filtering.

![image](https://user-images.githubusercontent.com/40002167/163818637-e418794d-2b76-4963-9d47-18c3fc60db6f.png)

**Comment by myangelkamikaze** [comment]
Groups will reload when docking a ship, using a bucket on a docked ship, and when loading a fleet from preset in the next release.

Both points should be covered by that, correct?

**Comment by y-jin-yoshihiko** [comment]
Yes, I think that will comply my wish, thank you.
