### ISSUE TITLE
Expedition ID is disappeared at Fleet State

### ISSUE THREAD

**Issue by MaitsukiKC** [gre4bee/ElectronicObserver#155]
Expedition ID is disappeared if fleet state is fighting spirit high at Fleet State. 
But it's fine when mouse hover.
![MQgYuMP9Qf](https://user-images.githubusercontent.com/36949440/163390209-d0fb2993-8026-4339-8e8b-3d9a993cfc1b.png)
![BY1CmRtule](https://user-images.githubusercontent.com/36949440/163390222-d39ae198-5bd5-40f6-84ba-df9ea4037df2.png)

**Comment by myangelkamikaze** [comment]
That's the intended behavior for those 2 options.
![image](https://user-images.githubusercontent.com/40002167/163538262-a497de32-826e-41eb-bd65-b1cda1056265.png)

**Comment by MaitsukiKC** [comment]
Oh, I get it. Thanks!
