### ISSUE TITLE
スクリーンショットの画像をズーム100％で保存する設定方法がありますか？

### ISSUE THREAD

**Issue by Genzoh-Wakaba** [gre4bee/ElectronicObserver#157]
日本語版七四式ではブラウザのズーム倍率が100％以外でも、スクリーンショットをショートカットボタンで保存した時に1200x720で保存できました。

七四式_ENでスクリーンショット画像を、常に100％で保存する為の設定方法がありますか？

※私は常にブラウザのズーム倍率を67％(Classic)にしてます。
この設定ではスクリーンショットを保存すると67％の804x482で保存されます。

**Comment by y-jin-yoshihiko** [comment]
今の仕様が実装されたときに、EN公式から画面で右クリックしてから保存で100%保存される、専ブラのボタンから保存で等倍はtodoだとアナウンスしていたと思います。

**Comment by myangelkamikaze** [comment]
https://twitter.com/74EOEN/status/1484786511174377476
https://twitter.com/74EOEN/status/1484787013576495105

It's still not possible to get the old behavior with WebView2 sadly.

**Comment by Genzoh-Wakaba** [comment]
ありがとうございます。
右クリックのメニューから保存します。
