### ISSUE TITLE
情報タブの問題

### ISSUE THREAD

**Issue by sasasa147852369** [gre4bee/ElectronicObserver#166]
ダークテーマを使用しているのですが情報タブ一面が不定期に点滅してとても邪魔です。

これが私の環境でのみか、他の人もなるかその辺りは存じませんが、一応報告申し上げます。

**Comment by myangelkamikaze** [comment]
Can you make a picture? I'm not really sure what could be going on.

**Comment by sasasa147852369** [comment]
23秒に起こっています。

https://user-images.githubusercontent.com/38494383/168038908-84d783ad-b6ba-4e61-8b42-4570a4c8448a.mp4

**Comment by myangelkamikaze** [comment]
Interesting, I've never seen that before. 情報 still needs to be reworked, so maybe it will be fixed after that.
Thank you for reporting!

**Comment by myangelkamikaze** [comment]
Version 5.1.5 has a reworked 情報 so this shouldn't be happening anymore. I suspect that the same problem should be happening in the ログ view however.

**Comment by myangelkamikaze** [comment]
Both 情報 and ログ are reworked now.
