### ISSUE TITLE
任務の「日英米合同水上艦隊、抜錨せよ！」について

### ISSUE THREAD

**Issue by KimidoriBoushi** [gre4bee/ElectronicObserver#167]
こちらなのですが、マウスポインターを合わせると全部S勝利、と出ておりますが、Aでいいみたいです。

**Comment by myangelkamikaze** [comment]
Should be fixed now. You might need to do an update check for the correct data to be reloaded.
![image](https://user-images.githubusercontent.com/40002167/168421524-5bf72513-99aa-4977-b1ca-aa6e6770adaa.png)
