### ISSUE TITLE
Suggestion: Change sort order in quest window when sorting by quest status

### ISSUE THREAD

**Issue by Heinrike** [gre4bee/ElectronicObserver#169]
Currently, when the quest window is sorted by quest status, the sort order goes 1) accepted but incomplete, 2) not accepted, 3) accepted and complete. I sort by status to keep all my accepted quests visible at the top of the list, but this causes unaccepted quests to down so I can't see completed quests without scrolling.

I think it would make more sense and also be more convenient if the sorting order went 1) accepted and complete, 2) accepted but incomplete, 3) not accepted

**Comment by myangelkamikaze** [comment]
Thanks for the suggestion!
It was already pointed out and implemented actually, it will be available in the next release.

![image](https://user-images.githubusercontent.com/40002167/169470420-555021da-05f1-48e2-a710-792c007c4e75.png)
