### ISSUE TITLE
Couldn't open release after 5.1.3

### ISSUE THREAD

**Issue by kosiverlar** [gre4bee/ElectronicObserver#171]
I tried to update my EO, but the EO in release 5.1.4 and 5.1.5 couldn't be opened. I double-clicked but there is nothing happened. I checked the ErrorReport folder but no log generated. (I unlocked the downloaded zip file so I think the copy is full, I also tried to delete the cache folder under `%appdata/local/` ).
Is there any way I could track more info for debug?

**Comment by myangelkamikaze** [comment]
It's probably due to the runtime bug: https://twitter.com/74EOEN/status/1512000989007650822

You can get the latest runtime from: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.5-windows-x64-installer

**Comment by kosiverlar** [comment]
Thanks! It's okay now.
