### ISSUE TITLE
log window output stop in 5.1.6

### ISSUE THREAD

**Issue by y-jin-yoshihiko** [gre4bee/ElectronicObserver#178]
In ver 5.1.6, the log window does not output the screenshot capture log, and after that, the log window does not seem to output any information until the 74N restart.

※I was relying strongly on this window information, so I rolled back to ver 5.1.5. So if it can do, I hope for individual fix releases.

**Comment by myangelkamikaze** [comment]
Thanks for the report.
We have the fix for this ready, it will be available in the next release.
