### ISSUE TITLE
情報タブが一瞬で消える

### ISSUE THREAD

**Issue by suikapple** [gre4bee/ElectronicObserver#182]
カーソルで指してるところに情報タグは出るが一瞬で消える。任務詳細、艦隊詳細などの情報をまともに使えません。

前々のバージョンでは発生しませんでしたが
いつの間にこの問題が発生しています

https://user-images.githubusercontent.com/106939824/172084252-6992f262-504c-4b01-850c-6a4a30322a4c.mp4

**Comment by myangelkamikaze** [comment]
https://github.com/gre4bee/ElectronicObserver/issues/158#issuecomment-1124533802

**Comment by suikapple** [comment]
治りました！
Thank you very much!
