### ISSUE TITLE
Icon Disappear

### ISSUE THREAD

**Issue by KahamaKirimaze** [gre4bee/ElectronicObserver#19]
i just see the icon at the first time of using ElectronicObserver.

**Comment by KahamaKirimaze** [comment]
![image](https://user-images.githubusercontent.com/64397629/80344178-596a5e00-8891-11ea-8bfc-e72440070600.png)

**Comment by myangelkamikaze** [comment]
Icons are in Assets.zip, can you check if you have that inside the EO folder?

**Comment by KahamaKirimaze** [comment]
Asset.zip is still there
what should i do?

**Comment by myangelkamikaze** [comment]
Make sure you have the latest version of EO, nothing about loading icons changed during versions but just to be safe.

When restarting EO try looking at the log (View>Log) if any error shows up.

**Comment by KahamaKirimaze** [comment]
hey i think last update make the icon wont disappear again!

**Comment by myangelkamikaze** [comment]
Alright.
