### ISSUE TITLE
Rework backend calculation of equipment fit bonus

### ISSUE THREAD

**Issue by Jebzou** [gre4bee/ElectronicObserver#214]
- Start by uploading to our Data repo a json containing all bonus data ?
- Use this data to make a collection of FitBonus
- Override the Sum operator of FitBonus 
- And make a tool to view/test bonus on ships ?

**Comment by myangelkamikaze** [comment]
- [ ] upload fit bonus json in the data repo (I'd just do a direct copy-paste, don't see a reason to change anything at the moment)
- [ ] make C# classes so the json can be parsed into something that's usable inside the app
- [ ] implement the logic for getting the fit bonus

Sum operator is just an implementation detail of the second task, so I didn't point it out.
I think a tool for displaying the fits is out of scope for what we need initially (#212), so I'd probably make a new issue for that.
