### ISSUE TITLE
Quests B150 and B151 are mislabeled

### ISSUE THREAD

**Issue by xharcar** [gre4bee/ElectronicObserver#65]
The quest translations list B151 as B150 and vice-versa, screenshots from quest.json and EO vs. EN KC wiki attached.

![B150_B151_json](https://user-images.githubusercontent.com/15063732/126529696-033c7cac-68ed-4a8a-a9b2-779ed91c59d4.JPG)

![B150_B151_wiki_vs_T74EO](https://user-images.githubusercontent.com/15063732/126529252-4177196c-7837-4707-9bfe-9e09b9ea6277.jpg)

**Comment by myangelkamikaze** [comment]
Nice find, wonder how I managed to do that...
Thanks for reporting!
