### ISSUE TITLE
WPF Fleet View doesn't show Sally Area Colors

### ISSUE THREAD

**Issue by gre4bee** [gre4bee/ElectronicObserver#68]
WPF Fleet view doesn't show Sally Area Colors as highlights in Fleet View
![kancolle-19-34-34-2208](https://user-images.githubusercontent.com/11538175/132125256-4ade2ce8-b2a6-4af2-83f8-183fd98fdf2b.png)
![kancolle-19-34-34-2209](https://user-images.githubusercontent.com/11538175/132125260-845caa78-281d-4c5b-9ac8-9a9a2ed00510.png)

**Comment by myangelkamikaze** [comment]
Fixed by 5b761fdf72e975ae8cfe56e119379c46c361e1f9
