### ISSUE TITLE
「next.を表示する」off not working fine

### ISSUE THREAD

**Issue by y-jin-yoshihiko** [gre4bee/ElectronicObserver#85]
When "next.を表示する" is set to OFF, 
only "next." is hidden 
and "Experience to the next level" is not hidden.
So the width is not shortened.

ver4
![スクリーンショット 2021-12-11 161155](https://user-images.githubusercontent.com/92554600/145668157-9cf26784-4121-4b6c-a824-fb5c95a596f1.png)

ver5 "next.を表示する"OFF
![スクリーンショット 2021-12-11 161211](https://user-images.githubusercontent.com/92554600/145668167-2ebf6a2f-2609-4721-aba8-1c41061e515c.png)

ver5 "next.を表示する"ON
![スクリーンショット 2021-12-11 161246](https://user-images.githubusercontent.com/92554600/145668170-c143356e-bd10-4e00-b1cf-a68e8d52a08e.png)

**Comment by myangelkamikaze** [comment]
The fix is implemented, it will be available in the next release.
