### ISSUE TITLE
Quest reward selection backdrop and buttons don't display

### ISSUE THREAD

**Issue by xharcar** [gre4bee/ElectronicObserver#89]
Usually, when a quest with a choice of rewards is completed, there's a frame over which the options are displayed, and once one is selected, buttons pop up to confirm/cancel(reconsider). This hasn't been the case for me since updating to 5.0.2.
![eo_view](https://user-images.githubusercontent.com/15063732/147281258-fc9c9b31-3f03-4460-b789-1faf56119648.png)
![eo_view_2](https://user-images.githubusercontent.com/15063732/147281263-4bd14811-8ace-4280-ac90-a946b06dd5c8.png)
Attached are also logs of when the screenshots above were taken; at first I thought the load of the aforementioned assets was taking longer for whatever reason and they would come up any second, so I proceeded as I normally would, but it's happened multiple times now.
[redacted.txt](https://github.com/gre4bee/ElectronicObserver/files/7770968/redacted.txt)
I've used KC3 and KCCP w/ EN patch until the 16th of December. I have not observed this issue using that configuration:
![kc3](https://user-images.githubusercontent.com/15063732/147282096-7ee5f808-34d9-4709-8246-66a71e206cff.JPG)

**Comment by myangelkamikaze** [comment]
EO doesn't do anything with game assets, aside from saving a copy if you have that enabled.
![image](https://user-images.githubusercontent.com/40002167/147312705-e4c007ac-ded5-4f48-afba-dad7ecbe328f.png)

You can try disabling that and see if it works. This would mean there's a problem when copying happens, and it would be an issue on our side. But I've never seen this happen before, so I doubt it.

From your last screenshot, it looks like you're modifying game assets. Check if the issue exists without this modification. If there's no issue with the regular game assets, the issue would be either with the app that's modifying the game assets or with the assets themselves, so that would need to get reported to whoever is maintaining those things.

**Comment by xharcar** [comment]
Thanks, I'll try disabling saving copies and see what happens.

**Comment by xharcar** [comment]
I've experimented some more. The results are as follows:
First, I unchecked "Other" as shown above:
![saving_others_disabled](https://user-images.githubusercontent.com/15063732/147348864-e9b4b948-cad3-4a97-a01d-cc6677571a30.JPG)
Then I double-checked modded assets in KC3 worked fine:
![bq6_kc3_en](https://user-images.githubusercontent.com/15063732/147348892-0af216f9-2662-4a66-ba4a-4798b3c139ca.JPG)
After removing the mod, I checked the original assets in KC3:
![bq6_kc3_unpatched](https://user-images.githubusercontent.com/15063732/147348928-c3c522c8-e38b-427e-bea1-eff7fd4218a5.JPG)
Thinking the issue might be with the data already saved by EO (something getting corrupted perhaps), I went and deleted all of it, then tried again:
![eo_cache_deleted_saving_other_off](https://user-images.githubusercontent.com/15063732/147348963-65292575-199d-4f20-922e-5f76604777a4.JPG)
And finally I checked "Other" again, just to see what would happen:
![eo_cache_deleted_saving_other_re_on](https://user-images.githubusercontent.com/15063732/147348992-64bc2bd3-fbdc-437d-af3a-accef968b698.JPG)
EO logs of the experiments:
[eolog_after_bq6_clear_redacted.txt](https://github.com/gre4bee/ElectronicObserver/files/7774138/eolog_after_bq6_clear_redacted.txt)

Ever since I started using EO, I've kept the EO cache and the KC3/KCCP/EN mod files in separate directories. Per my KC3 settings file:
"cacheLocation": "D:\\KanColle\\KCCacheProxy\\ProxyData\\cache"
So I don't see how changes in one could have an effect on the other.

**Comment by myangelkamikaze** [comment]
Hmm, I wonder if CefSharp got confused and broke its cache somehow...
(after I wrote everything I realized it might have cached the modified file, and now loads it even when the mod is disabled, so it's probably a good idea to check both with and without mod while having cache disabled)

A way to check this would be to temporarily disable its cache and see if the assets load. You can do this from the browser menu, or just press F12 while the browser is focused:
![image](https://user-images.githubusercontent.com/40002167/147367595-67ba903c-e1a4-4cbb-a43b-7e88812e7ba6.png)

In devtools go under "Network" and enable the "Disable cache" option, you'll need to keep devtools open while using this option.
![image](https://user-images.githubusercontent.com/40002167/147367618-037cf453-5358-4e6a-a409-45a589a7ed0e.png)

After that, try going to the quest screen again and see what you get.

**Comment by xharcar** [comment]
Done and fixed, that set me on the right path.
I turned off the cache, and that seemed to have fixed it:
![bq13_cache_off_nomod](https://user-images.githubusercontent.com/15063732/147384185-7e78907e-86f5-45d5-bc73-73e89ceed614.png)

Here I figured maybe there was something up with the cache, and sure enough, for whatever reason the PNG image and the JSON file required for everything to display correctly were missing, I don't know why:
![required_png_uncached_questionmark](https://user-images.githubusercontent.com/15063732/147384214-99aaab72-f244-47e6-b228-36469d62e5f9.png)

So I manually saved both files into that directory, and tried again, cache on, and it all displayed fine:
![bq13_cache_on_after_download](https://user-images.githubusercontent.com/15063732/147384228-5150ac02-173d-440d-99f3-1e0a4d0753ea.png)

Thanks for taking the time to help me with this, especially considering the timing.

**Comment by myangelkamikaze** [comment]
Glad to see you found a solution.
Thanks for the detailed replies!
