### ISSUE TITLE
The latest screenshot output is locked.

### ISSUE THREAD

**Issue by y-jin-yoshihiko** [gre4bee/ElectronicObserver#90]
When I get a screenshot using 74en (1)(2) and afterwards try to delete it, but it is locking and it can' t be deleted (3).
I think it's the 74en's original "last screenshot" function is locking the file(4).

(1)
![20211224_14162575](https://user-images.githubusercontent.com/92554600/147331162-a5caf721-9bf8-4c90-b9d6-48488f8afe26.jpg)
(2)
![スクリーンショット 2021-12-24 141645](https://user-images.githubusercontent.com/92554600/147331375-76319302-af62-4fab-9567-12b0f8a6e9b1.png)

(3)
![スクリーンショット 2021-12-24 141753](https://user-images.githubusercontent.com/92554600/147331428-98e72a9e-7591-4c4a-bf52-5bfe97deed5f.png)
(4)
![スクリーンショット 2021-12-24 141711](https://user-images.githubusercontent.com/92554600/147331497-11973763-ca1b-467d-bff3-8af20937beca.png)

Please fix 74en so that it doesn't lock the file, or add the function to delete the "last screenshot" on 74en.

※This is needed when a screenshot is missed.

**Comment by myangelkamikaze** [comment]
You're probably right, this should be a problem with the last screenshot feature.

I think the best thing to do here is adding a button to delete the last image, and maybe load the one before that into preview.
