### ISSUE TITLE
(In Japanese) The width of the buttons in the group view is too narrow.

### ISSUE THREAD

**Issue by NaokiSato102** [gre4bee/ElectronicObserver#92]
As shown in the attached figure, the text is obscured by the narrow width of the button. Changing the text size does not improve the situation since the size changes proportionally.
![image](https://user-images.githubusercontent.com/27545766/147928854-40f8483c-e593-4749-b852-eb4e296027c7.png)

**Comment by NaokiSato102** [comment]
#74 I had a similar problem. careless

**Comment by myangelkamikaze** [comment]
Thanks for the report.
We added a fix now, which will be available in the next version (probably tomorrow).
